[package]
name = "vulcast-rtc"
version = "0.1.0"
authors = ["Gordon Guan <admin@netdex.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulcast-rtc-sys = { path="../vulcast-rtc-sys" }
